### ISSUE TITLE
Request: Implementing retry mechanism on throttle failures

### ISSUE THREAD

**Issue by timr11** [ConvertAPI/convertapi-library-go#12]
My organization is subscribed to the Business tier. We would like to perform large batches of conversions in parallel. In theory we have unlimited bandwidth, I'd like to implement a retry policy on 503 throttle failures. In this library, there doesn't appear to be a way of accessing the HTTP response after a call is made to the ConvertAPI REST API. It would be helpful to expose the HTTP response to allow for custom error handling.

**Comment by JonasJasas** [comment]
We will internally discuss this and will let you know about the decision.

**Comment by JonasJasas** [comment]
Would it be for you acceptable, for now to use `ConvertPath` method to get an error? https://github.com/ConvertAPI/convertapi-go/blob/master/examples/simple/main.go

**Comment by JonasJasas** [comment]
Every public method on `Result` struct returns `errors`, you can use it too to get an error.

**Comment by tomasr78** [comment]
Is your question answered, @timr11?
